// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqrdbiuwfogjcnlbqxyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcmRiaXV3Zm9namNubGJxeHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzI5NjMsImV4cCI6MjA2NzQ0ODk2M30.35QSJXTdh73fXcgMYHVKjmRFQNv8FSdBH5AGIHP5CBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});